### ISSUE TITLE
Building qubes-windows-tools

### ISSUE THREAD

**Issue by brendanhoar** [tabit-pro/Qway-qubes-repo#1]
Not being familiar with mock, I couldn't bridge the gap between the successful run of mock for the source package for qubes-windows-tools (via mock -r fedora-qbs.cfg --buildsrpm --scm-enable -scm-option package= )  and the generation of the binary rpm via mockchain/mock --chain.

Via Qubes forum, I found the solution here: https://github.com/0rb677/dotfiles

which is as follows, after increasing private storage on your fedora VM or template, of course:

```
sudo dnf install mock
sudo groupmems -a user -g mock
sudo mount -o remount,dev /dev/xvdb /home
git clone https://github.com/tabit-pro/qway-qubes-repo
mock -n -r qway-qubes-repo/fedora-qbs.cfg --rootdir /home/user/temp --resultdir \
/home/user/rpms --sources qway-qubes-repo/qubes-windows-tools/ --spec \
qway-qubes-repo/qubes-windows-tools/qubes-windows-tools.spec
```

And utilize the .noarch.rpm found in /home/user/rpms/ when it completes.

So...suggesting some additional examples in the Readme.md would be useful for mock newbies. :)

B

Thanks,
Brendan

PS - also - THANK YOU SO MUCH FOR ALL THE WORK THAT WENT INTO THIS. <- should have said this first.

**Comment by easydozen** [comment]
Thanks for your nice feedback, Brendan. 
I've updated Readme on your request. Let me know if something else should be better described.

**Comment by tlaurion** [comment]
@brendanhoar ? following down from https://github.com/elliotkillick/qvm-create-windows-qube/issues/15#issuecomment-811882766 would love to hear your input on a possible merge and PR?

**Comment by arkenoi** [comment]
tried building and it did not work for me either :( first problem was outdated fedora template (32, up to date is 34). fixed this. then make was missing from buildrequires -- fixed this too. then it fails because of multiple definition of LOG_LEVEL and now I give up. Could i just have binaries please?

**Comment by jevank** [comment]
@arkenoi QWT builds for dom0 which is still fedora 32, so it don't need to fix.

**Comment by jevank** [comment]
Also you can build it with qubes-builder, look at this [repo](https://github.com/tabit-pro/qubes-windows-tools-cross)

**Comment by jevank** [comment]
Close, latest QWT is here https://github.com/tabit-pro/qubes-windows-tools-cross
